### ISSUE TITLE
Warning: DisplayState: Exception occurred in callback function.

### ISSUE THREAD

**Issue by HelgeGitHub** [kkujansuu/gramps#31]
Every time I add an sub-filter using the Edit button I get these messages if I close the Define Filter dialogue with OK (nothing happens with Cancel):
Warning: DisplayState: Exception occurred in callback function.
Traceback (most recent call last):
  File "C:\Programme\GrampsAIO64-5.1.5\gramps\gen\utils\callback.py", line 409, in emit
    fn(*args)
  File "C:\Programme\GrampsAIO64-5.1.5\gramps\plugins\FilterParams\FilterParams.py", line 183, in filters_changed
    self.populate_filters(namespace, self.current_filtername)
  File "C:\Programme\GrampsAIO64-5.1.5\gramps\plugins\FilterParams\FilterParams.py", line 169, in populate_filters
    self.combo_filters.get_model().clear()
AttributeError: 'NoneType' object has no attribute 'clear'

Win10Prof, German, GrampsAIO64-5.1.5

**Comment by kkujansuu** [comment]
Yes, this occurs after the tool is closed and reopened in the same session. Will be fixed in the next version.
