### ISSUE TITLE
Add multiple events quick view Unhandled exception selecting an Event

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#46]
In the Add multiple events (for Person or Family), the Select (Share) or Add workflow generates an error when the Event Editor dialog is "OK"d

```
44241124: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/home/districtsupport/.local/lib/python3.11/site-packages/gramps/gui/editors/editeventref.py", line 334, in ok_clicked
    self.update(self.source_ref, self.source)
  File "/home/districtsupport/.gramps/gramps52/plugins/add-multiple-events/add-multiple-events.py", line 368, in eventref_callback
    self.add_event_to_dialog(eventref, event)
  File "/home/districtsupport/.gramps/gramps52/plugins/add-multiple-events/add-multiple-events.py", line 285, in add_event_to_dialog
    place = self.db.get_place_from_handle(event.place)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/districtsupport/.local/lib/python3.11/site-packages/gramps/gen/db/generic.py", line 1356, in get_place_from_handle
    return self._get_from_handle(PLACE_KEY, Place, handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/districtsupport/.local/lib/python3.11/site-packages/gramps/gen/db/generic.py", line 1336, in _get_from_handle
    raise HandleError("Handle is empty")
gramps.gen.errors.HandleError: Handle is empty

```

**Comment by kkujansuu** [comment]
Fixed in v1.2.
